### ISSUE TITLE
Flow border disappears on hover

### ISSUE THREAD

**Issue by fcastill** [TIBCOSoftware/flogo-web#960]
**Issue:**

In application detail page, when hovering over a flow card the border disappears.

![screen shot 2019-01-04 at 3 16 04 pm](https://user-images.githubusercontent.com/17577698/50715815-c0785980-1033-11e9-9b63-9c9e65d8af67.png)

Can only reproduce in Chrome, tried Chrome v71.0.3578.98.

It seems to be a Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=878195

I was able to reproduce it externally, it only happens sometimes so you might need to reload a couple of times.

https://codepen.io/fabkast/pen/LMdyyK

**Additional observations**
In the codepen if border-radius is set for all corners instead of declaring it separately then the issue seems to go away.

In the current Flogo Web UI:

```css
/* Declarations as they are in the flogo UI, issue is reproducible */
.card {
  border-bottom-left-radius: 4px;
  border-bottom-right-radius: 4px;
  border-top-right-radius: 4px;
}
```

If instead we use this, the issue seems to go away:
```css
.card {
  border-radius: 4px;
  /* border-bottom-left-radius: 4px; */
  /* border-bottom-right-radius: 4px; */
  /* border-top-right-radius: 4px; */
}
```
